#[build]
#target = "x86_64-unknown-linux-gnu"
#
#[target.x86_64-unknown-linux-gnu]
#linker = "/usr/bin/clang-18"
#rustflags = ["-C", "relocation-model=static", "-C", "link-arg=--ld-path=/usr/bin/mold"]
# rustflags = ["-C", "relocation-model=static", "-C", "link-arg=--ld-path=/usr/bin/mold", "-Clink-arg=-Wl,--no-rosegment"]

[profile.dev]
debug = 0
